### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by fenrir-5** [riverdi/riverdi-eve#1]
Hey there,

Guys, I'm sorry to contact you through GitHub but there is no other way to send you message since none of your forms is working.

I've just tried to register and launch an order but unfortunately, reCaptcha doesn't work and this code is shown: "Error for site owner: Invalid site key".
It looks like the script is not properly implemented.

Please let me know when you fix it so I can register and place a new order.

Thank you

**Comment by riverdi** [comment]
Problem solved on our site.
Sorry for trouble
