### ISSUE TITLE
Compilation Linux fails

### ISSUE THREAD

**Issue by ymebrugts** [riverdi/riverdi-eve#3]
Dear Sir/Madam,

The compilation for Linux fails unfortunately. It's a completely clean clone from git. 
![Screenshot from 2021-08-12 10-16-43](https://user-images.githubusercontent.com/36673314/129162833-4ea635bb-4edc-4ee5-9d10-56bbda69860b.png)

I've run through the defines and they seem fine. Is this a problem with the library or the environment not being set up correctly?

Defines: 
DEFS = -DLINUX_PLATFORM
DEFS += -DBUFFER_OPTIMIZATION

DEFS += -DEVE_2
DEFS += -DCTP_50

Best regards,
Yme

**Comment by ymebrugts** [comment]
I found it in module.h EVE_4 + IPS_70 + EVE_4_EXTERNAL_OSC is defined as standard but it shouldn't be. This causes the errors.

**Comment by clear-sky** [comment]
hi 
how can it be fixed?

**Comment by ymebrugts** [comment]
Hi

What I did was comment out this in modules.h

![image](https://user-images.githubusercontent.com/36673314/226140622-123ecd7e-fdea-4153-bf2a-fe95963d3716.png)

**Comment by clear-sky** [comment]
hi thanks for the answer
i did this trick before but when i try to run it give this error:

gpio/export: No such file or directory
Aborted (core dumped)

please note that i run this app on a normal linux desktop( not linux-based Single Board Computer)  this means that i have not any available spi port
am i right?
