### ISSUE TITLE
Writing 16 bits to an 8 bit var

### ISSUE THREAD

**Issue by breshead** [riverdi/riverdi-eve#6]
https://github.com/riverdi/riverdi-eve/blob/c3cdf3737bcdd0325097c73eb60c3a4816088c86/app_layer/App_Common.c#L859

Should be (probably?)
~~~
        Gpu_Hal_Wr8(phost, REG_GPIO_DIR, 0x80);
~~~

Looks like it is fixed in the CPP arduino version.. Only they use 0xff
[riverdi-eve-arduino/App_Common.cpp at master · riverdi/riverdi-eve-arduino](https://github.com/riverdi/riverdi-eve-arduino/blob/master/App_Common.cpp)
~~~
Gpu_Hal_Wr8(phost, REG_GPIO_DIR,0xff);
~~~

**Comment by lukasz-skalski** [comment]
Thanks for letting know - should be already fixed with: db78aa7428e21d45b106c2ea30d01922a353e9d9
