### ISSUE TITLE
Broken links in ReadMe.md

### ISSUE THREAD

**Issue by SamHerts** [riverdi/riverdi-eve#9]
https://github.com/riverdi/riverdi-eve/blob/c3cdf3737bcdd0325097c73eb60c3a4816088c86/README.md?plain=1#L15-L16

Both links to RiverDi products are broken in the ReadMe.md.

The Riverdi Revelation board seems to be completely missing, but a data sheet does still exist:
https://riverdi.com/wp-content/uploads/datasheet/Revelation_Board_Datasheet_Rev.1.1.pdf

The Hermes Board also is completely missing, but an article was written about it:
https://riverdi.com/blog/hermes-board-spi-usb-bridge-board-2/

**Comment by lukasz-skalski** [comment]
Fixed - thanks.

Riverdi Revelation Board and Hermes Board are no longer supported and has been replaced by STM32 Evaluation Board (https://riverdi.com/product/stm32-evaluation-board/). STM32 Evaluation Board allows you to work with a display in three modes:

- from STM32F469 via RiBUS (SPI) to EVE displays (support for new STM32F469 soon will be part of riverd-eve repository),

- from USB via FT232H bridge to RiBUS (SPI) and then to EVE displays (the same way like with Hermes Board and Makefile.win32),

- from STM32F469 LTDC TFT controller to Riverdi HB IPS displays with RGB interface and to Riverdi HB IPS displays with LVDS&DSI interfaces with serializer (this "non-EVE" mode is not supported in this repository).
